### PR TITLE
fix: using env production mode

### PR DESCRIPTION
**Pull request by masb0ymas**
ketika menjalankan NextJs dengan menggunakan `npm run start`  env yang kebaca hanya `.env.production` dan juga agar `process.env` nya running musti di set juga di `next.config.js`

### CODE REVIEW

**Comment by chornos13** [comment]
Emang perlu dipassing di next.config.js?

**Comment by masb0ymas** [comment]
> Emang perlu dipassing di next.config.js?

kalo di run pake `npm run dev` dia ngebaca .env.development, nah kemaren udah aku coba pake `.env.production` si .env nya ke baca saat `npm run start` tapi process.env nya gk masuk, dan setelah di cari ada beberapa solusi, 
1. load env ke `next.config.js`
2. di setup langsung env nya ke next.config.js

nah yg solusi pertama aku udah nyoba tapi belum ke baca process.env nya, yg kebaca solusi kedua

**Comment by chornos13** [comment]
https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables
Udah baca di situ ji ?

> Note: In order to keep server-only secrets safe, Next.js replaces process.env.* with the correct values at build time. This means that process.env is not a standard JavaScript object, so you’re not able to use object destructuring. Environment variables must be referenced as e.g. process.env.NEXT_PUBLIC_PUBLISHABLE_KEY, not const { NEXT_PUBLIC_PUBLISHABLE_KEY } = process.env.

relate nggak dgn problem itu ?

**Comment by masb0ymas** [comment]
> https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables
> Udah baca di situ ji ?
> 
> > Note: In order to keep server-only secrets safe, Next.js replaces process.env.* with the correct values at build time. This means that process.env is not a standard JavaScript object, so you’re not able to use object destructuring. Environment variables must be referenced as e.g. process.env.NEXT_PUBLIC_PUBLISHABLE_KEY, not const { NEXT_PUBLIC_PUBLISHABLE_KEY } = process.env.
> 
> relate nggak dgn problem itu ?

udah aku ikutin tuh di docs next js gimana cara dia pake .env
akan tetapi masih belum kebaca juga kalo udah di run `npm run start` udah aku coba pake `NEXT_PUBLIC_URL_ENV` masih undefined. 

Trus ada blog yg bahas environment ketika run production, https://medium.com/frontend-digest/environment-variables-in-next-js-9a272f0bf655

**Comment by masb0ymas** [comment]
Dan ternyata `.env.local` ini dia cuma run di server si next js nya
URL_ENV yg di `constant.js` itu berada di sisi client. 

makanya kalo mau ke baca di constant.js nya musti di tambahkan code ini :
```sh

module.exports = {
  ...imageConfig,
  env: {
    URL_ENV: process.env.URL_ENV,
  },
}
```

**Pull request closed without merging**
